const questions = [
  {
    id: 1,
    question: "What is the correct way to declare a variable in JavaScript?",
    options: ["var x = 5;", "variable x = 5;", "v x = 5;", "dim x = 5;"],
    answer: "var x = 5;",
  },
  {
    id: 2,
    question: "Which keyword is used to define a constant in JavaScript?",
    options: ["const", "let", "var", "define"],
    answer: "const",
  },
  {
    id: 3,
    question: "What does '===' check in JavaScript?",
    options: ["Value and type", "Only value", "Only type", "Reference"],
    answer: "Value and type",
  },
  {
    id: 4,
    question: "Which method is used to add an element to the end of an array?",
    options: ["push()", "pop()", "shift()", "unshift()"],
    answer: "push()",
  },
  {
    id: 5,
    question: "What is the output of: typeof null?",
    options: ["object", "null", "undefined", "number"],
    answer: "object",
  },
  {
    id: 6,
    question: "Which function is used to parse a string to an integer?",
    options: ["parseInt()", "parseFloat()", "Number()", "toInt()"],
    answer: "parseInt()",
  },
  {
    id: 7,
    question: "What does the 'this' keyword refer to in JavaScript?",
    options: [
      "Current object",
      "Global object",
      "Parent object",
      "Window object",
    ],
    answer: "Current object",
  },
  {
    id: 8,
    question: "Which loop executes at least once?",
    options: ["do...while", "while", "for", "forEach"],
    answer: "do...while",
  },
  {
    id: 9,
    question: "What is a closure in JavaScript?",
    options: [
      "Function with access to outer scope",
      "Closed function",
      "Anonymous function",
      "Arrow function",
    ],
    answer: "Function with access to outer scope",
  },
  {
    id: 10,
    question: "Which method removes the last element from an array?",
    options: ["pop()", "push()", "shift()", "slice()"],
    answer: "pop()",
  },
  {
    id: 11,
    question: "What does NaN stand for?",
    options: [
      "Not a Number",
      "Null and None",
      "New Array Number",
      "Negative Number",
    ],
    answer: "Not a Number",
  },
  {
    id: 12,
    question: "Which operator is used for strict equality?",
    options: ["===", "==", "=", "!="],
    answer: "===",
  },
  {
    id: 13,
    question: "What is the purpose of JSON.stringify()?",
    options: [
      "Convert object to string",
      "Convert string to object",
      "Parse JSON",
      "Validate JSON",
    ],
    answer: "Convert object to string",
  },
  {
    id: 14,
    question: "Which method is used to combine two arrays?",
    options: ["concat()", "merge()", "join()", "combine()"],
    answer: "concat()",
  },
  {
    id: 15,
    question: "What is the default value of an uninitialized variable?",
    options: ["undefined", "null", "0", "false"],
    answer: "undefined",
  },
  {
    id: 16,
    question: "Which statement is used to exit a loop?",
    options: ["break", "exit", "return", "stop"],
    answer: "break",
  },
  {
    id: 17,
    question: "What does the 'new' keyword do?",
    options: [
      "Creates object instance",
      "Declares variable",
      "Defines function",
      "Imports module",
    ],
    answer: "Creates object instance",
  },
  {
    id: 18,
    question: "Which method converts a string to lowercase?",
    options: ["toLowerCase()", "toLower()", "lower()", "lowerCase()"],
    answer: "toLowerCase()",
  },
  {
    id: 19,
    question: "What is an arrow function?",
    options: ["() => {}", "function() {}", "=> function {}", "arrow() {}"],
    answer: "() => {}",
  },
  {
    id: 20,
    question: "Which method finds an element in an array?",
    options: ["find()", "search()", "locate()", "get()"],
    answer: "find()",
  },
  {
    id: 21,
    question: "What does the spread operator (...) do?",
    options: [
      "Expands array elements",
      "Combines arrays",
      "Loops array",
      "Creates array",
    ],
    answer: "Expands array elements",
  },
  {
    id: 22,
    question: "Which method checks if all elements pass a test?",
    options: ["every()", "some()", "all()", "check()"],
    answer: "every()",
  },
  {
    id: 23,
    question: "What is the output of: '5' + 3?",
    options: ["53", "8", "35", "error"],
    answer: "53",
  },
  {
    id: 24,
    question: "Which keyword creates a block-scoped variable?",
    options: ["let", "var", "const", "block"],
    answer: "let",
  },
  {
    id: 25,
    question: "What does Promise.all() do?",
    options: [
      "Waits for all promises",
      "Resolves first promise",
      "Rejects all promises",
      "Creates promise",
    ],
    answer: "Waits for all promises",
  },
  {
    id: 26,
    question: "Which method creates a new array from calling a function?",
    options: ["map()", "filter()", "reduce()", "forEach()"],
    answer: "map()",
  },
  {
    id: 27,
    question: "What is the difference between let and var?",
    options: ["Scope", "Type", "Speed", "Memory"],
    answer: "Scope",
  },
  {
    id: 28,
    question: "Which method removes the first element of an array?",
    options: ["shift()", "pop()", "unshift()", "remove()"],
    answer: "shift()",
  },
  {
    id: 29,
    question: "What does async/await do?",
    options: [
      "Handles promises",
      "Creates loops",
      "Defines functions",
      "Imports modules",
    ],
    answer: "Handles promises",
  },
  {
    id: 30,
    question: "Which method tests if at least one element passes?",
    options: ["some()", "every()", "any()", "test()"],
    answer: "some()",
  },
  {
    id: 31,
    question: "What is destructuring in JavaScript?",
    options: [
      "Extracting values from objects/arrays",
      "Destroying objects",
      "Creating objects",
      "Combining objects",
    ],
    answer: "Extracting values from objects/arrays",
  },
  {
    id: 32,
    question: "Which method returns a string from an array?",
    options: ["join()", "toString()", "concat()", "stringify()"],
    answer: "join()",
  },
  {
    id: 33,
    question: "What does the filter() method do?",
    options: [
      "Creates filtered array",
      "Removes elements",
      "Sorts array",
      "Finds element",
    ],
    answer: "Creates filtered array",
  },
  {
    id: 34,
    question: "Which symbol denotes template literals?",
    options: [
      "Backticks ``",
      "Single quotes ''",
      'Double quotes ""',
      "Parentheses ()",
    ],
    answer: "Backticks ``",
  },
  {
    id: 35,
    question: "What is the purpose of use strict?",
    options: [
      "Enables strict mode",
      "Imports module",
      "Defines variable",
      "Creates function",
    ],
    answer: "Enables strict mode",
  },
  {
    id: 36,
    question: "Which method converts JSON string to object?",
    options: ["JSON.parse()", "JSON.stringify()", "parseJSON()", "toObject()"],
    answer: "JSON.parse()",
  },
  {
    id: 37,
    question: "What does the reduce() method do?",
    options: [
      "Reduces array to single value",
      "Removes elements",
      "Filters array",
      "Maps array",
    ],
    answer: "Reduces array to single value",
  },
  {
    id: 38,
    question: "Which keyword is used to handle errors?",
    options: [
      "try...catch",
      "error...handle",
      "catch...error",
      "handle...error",
    ],
    answer: "try...catch",
  },
  {
    id: 39,
    question: "What is the output of: Boolean('')?",
    options: ["false", "true", "undefined", "null"],
    answer: "false",
  },
  {
    id: 40,
    question: "Which method checks if array includes a value?",
    options: ["includes()", "contains()", "has()", "exists()"],
    answer: "includes()",
  },
  {
    id: 41,
    question: "What does the ternary operator look like?",
    options: [
      "condition ? true : false",
      "if ? then : else",
      "condition && true || false",
      "? condition : result",
    ],
    answer: "condition ? true : false",
  },
  {
    id: 42,
    question: "Which method returns index of element?",
    options: ["indexOf()", "findIndex()", "searchIndex()", "getIndex()"],
    answer: "indexOf()",
  },
  {
    id: 43,
    question: "What is event bubbling?",
    options: [
      "Event propagation upward",
      "Event propagation downward",
      "Event stopping",
      "Event triggering",
    ],
    answer: "Event propagation upward",
  },
  {
    id: 44,
    question: "Which method creates a shallow copy of array?",
    options: ["slice()", "splice()", "copy()", "clone()"],
    answer: "slice()",
  },
  {
    id: 45,
    question: "What does Object.keys() return?",
    options: [
      "Array of keys",
      "Array of values",
      "Object copy",
      "Key-value pairs",
    ],
    answer: "Array of keys",
  },
  {
    id: 46,
    question: "Which operator checks for null or undefined?",
    options: ["??", "||", "&&", "!"],
    answer: "??",
  },
  {
    id: 47,
    question: "What is the purpose of setTimeout()?",
    options: [
      "Delays code execution",
      "Creates loop",
      "Stops execution",
      "Measures time",
    ],
    answer: "Delays code execution",
  },
  {
    id: 48,
    question: "Which method reverses an array?",
    options: ["reverse()", "flip()", "invert()", "backward()"],
    answer: "reverse()",
  },
  {
    id: 49,
    question: "What does the 'instanceof' operator check?",
    options: [
      "Object type",
      "Variable type",
      "Function type",
      "Primitive type",
    ],
    answer: "Object type",
  },
  {
    id: 50,
    question: "Which method sorts an array?",
    options: ["sort()", "order()", "arrange()", "organize()"],
    answer: "sort()",
  },
];
